# Generated by Django 4.1.1 on 2022-09-20 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="responsible_for_updating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
