# Generated by Django 4.1.1 on 2022-09-20 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0003_restaurant_created_at_restaurant_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="responsible_for_updating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
